### ISSUE TITLE
Design mock-up for messages searching screen

### ISSUE THREAD

**Issue by catalin-sc** [SpamExperts/mobile-app#12]
http://bit.ly/AppMessagesSearchScreen

**Comment by lorentina** [comment]
@nicolaeSE 

- On Incoming and Outgoing, use the "Clear Search" button, then make a search where you modify "From date" and "To date". Close the app and re-open it. Notice that search fields reset only for "Incoming" (this happens only when using the "Clear Search" button - before re-opening the app). This does not happen if the "Clear Search" button is not used.

- When refreshing to see new emails, only "To date" resets itself to the current date and time (on both Incoming and Outgoing). "From date" should reset as well.
 
- User should not be allowed to set "From date" somewhere in the future and "To date" somewhere in the past (Eg. not be able to set "From date" to 2018, and "To date" to 2016).

**Comment by nicolaeSE** [comment]
@catalin-sc confirmed that the Clear button should only clear the form and it should not perform a search with the default values. This has been adjusted in the last commit
It is normal when using pull to refresh to get the newest results without changing any of the user's search criteria except the 'to date'.
In the previous commit I've updated the datetime plugin we are using and added a limit so the user can't select anything in the future. I think @alexkiro can confirm that there is no need to set such a limit for the past. Regarding setting 'From date' > 'To date' - I don't think we should protect against such users mistakes

**Comment by lorentina** [comment]
Verified.
