### ISSUE TITLE
Pressing the back key on the mobile device leads to the login page 

### ISSUE THREAD

**Issue by Agoodfella** [SpamExperts/mobile-app#29]
If you log in as a user(super-admin/domain/email user) and go to the incoming quarantine section. You can press the "back" key on the mobile device until you get back to the login page while still being logged in.
Reproduction steps:

1. Login as e.g. super-admin user
2. Go to the incoming quarantine section of the app
3. Press the back key until the login page is revealed
You could try entering a different user and log in again but the user displayed after another successful login would be the initial one from step 1. 

Note: It would probably be better if the login page is erased from the app "history" so the back key wouldn't lead back to it, or a notice message warning the user that if he wants to get back to the login page , a logout will occur.
Issue occurred on Android device OS version 6.0.1.

**Comment by georges96** [comment]
The adjustment fixed the issue. The back key is not going to the login page anymore if the back key is pressed several times.
