### ISSUE TITLE
Bulk-refresh

### ISSUE THREAD

**Issue by CosminBadea1** [SpamExperts/mobile-app#30]
If you pull to refresh while in bulk mode and new messages are received the number of selected messages will remain in the More action bar. The previously selected messages don t appear checked after refresh, but the action buttons from the bottom side don t disappear.

Steps to reproduce:
- bulk one or more messages;
- send a new message to quarantine;
- pull to refresh

**Comment by CosminBadea1** [comment]
If you pull to refresh while in bulk mode and new messages are received the app will display several duplicates of the received messages after you uncheck and pull to refresh.

**Comment by nicolaeSE** [comment]
I was unable to reproduce this behavior
