### ISSUE TITLE
scrolling to top and bottom changes subject of last email

### ISSUE THREAD

**Issue by ashleyse2016** [SpamExperts/mobile-app#35]
### Version information

?
### Steps to replicate

 1. install android app
 2. Login to domain
 3. Show quarantine for last week
 4. Scroll to top, then scroll to bottom , note the last message subject
 5. Do it again subject changed to subject of other message

### Actual result

Subject changes to other message

### Expected result

To see the same subject

### Other notes

Screen shots available on request.

**Comment by nicolaeSE** [comment]
This is related to #36. Closing this as duplicate.
