### ISSUE TITLE
Subjects in the message list doesn't match the subject in the message view 

### ISSUE THREAD

**Issue by alexkiro** [SpamExperts/mobile-app#36]
### Version information

1.0.2

### Steps to replicate

 1. Add domain
 1. Add messages in the quarantine with different subject each
 1. Add domain user
 1. Login with the domain users for in the mobile app
 1. Notice messages look okay
 1. Switch the search from last 24 hours to last week and hit Search

### Actual result

Notice that the Subject in the list doesn't match up with the subject after viewing the message. After viewing a messages with "Subject 1" in the list, you can see after viewing the message that it is actually different. 

### Expected result

The list should match the view. 

### Other notes

 - This replicates on both Android and iOS. 
 - Switching the search back to 24 hours doesn't fix the issue

**Comment by Agoodfella** [comment]
Verified that the initial issue cannot be reproduced after the fix was applied.
