### ISSUE TITLE
Mobile app shows blank screen after trying to login as admin

### ISSUE THREAD

**Issue by nicolaeSE** [SpamExperts/mobile-app#37]
We currently don't offer support for admin users, however we should have a nicer way of dealing with such wrong logins.

### Version information
1.0.4

### Steps to replicate

 1. Try to log in as admin
 2. The login page gets stuck
 3. Close the app and reopen
 4. Notice the blank screen

### Expected result
 There should be a notification that informs the user that admins are not supported.

**Comment by nicolaeSE** [comment]
I think this no longer occurs. Can anyone test it and close the ticket?

**Comment by georges96** [comment]
Tested. It's not stucking anymore. There is a popup message informing the user that admins are not yet supported.
