### ISSUE TITLE
Show "cancel" button when there is no internet connection

### ISSUE THREAD

**Issue by dreasvandonselaar** [SpamExperts/mobile-app#38]
### Version information

1.0.4
### Steps to replicate

 1. Try and access without internet connection
 1. A "Recheck" button is shown, but no button to cancel (or exit the app?) 

### Other notes

![image](https://user-images.githubusercontent.com/4503663/27028860-73accee0-4f66-11e7-93b8-5dd5d2f80802.png)

**Comment by tonyandrewmeyer** [comment]
What would "cancel" do? There's no offline mode to fall back to, so it seems like there's nothing the app could usefully show you if you cancelled.

(In terms of exiting, on iOS, you 'exit' by pushing the home button. Is that not the same on Android?)

**Comment by nicolaeSE** [comment]
I don't see a point of having a cancel button. The app should be closed the way you normally close any app.

**Comment by dreasvandonselaar** [comment]
Hmm, indeed other apps also have no cancellation option. If this is not consistent with the way things should work feel free to reject the enhancement suggestion :)
