### ISSUE TITLE
Viewing a message and selecting the raw tab before the load is complete leads to Service Unavailable

### ISSUE THREAD

**Issue by Agoodfella** [SpamExperts/mobile-app#39]
### Version information
latest

### Steps to replicate

 1. Login as a domain user with incoming traffic 
 2. Go to the incoming section
 3. Select one of the messages to view 
 4. Once in the view window switch from the Plain tab to Normal and Raw, all this before the message is fully loaded.

### Actual result

You'll notice a `Service unavailable` error message.

### Expected result

The error should not be displayed during this operation.

### Other notes

Tests were performed on devices running IOS 10.3.2 and Android 6.0 .

**Comment by cristinav74** [comment]
Issue tested.
