### ISSUE TITLE
Add whitelabel support

### ISSUE THREAD

**Issue by ashleyse2016** [SpamExperts/mobile-app#41]
As some people have branding, there should be a whitelabel version, or a way that people can brand this.  Or possibly provide instructions on what needs to be changed to re-build this for branding.

**Comment by tonyandrewmeyer** [comment]
A whitelabel solution is not compatible with the Play/App Stores.

The GitHub project already has instructions for how to build a custom version, if clients want to do that.

See [recent discussion](https://discourse.seinternal.com/t/planning-the-mobile-apps-ui/825?u=tony) and [more detailed earlier discussion](https://discourse.seinternal.com/t/what-should-be-the-feature-set-for-the-ios-android-applications/299/13).
