### ISSUE TITLE
specific date formatting removes date and time details from app

### ISSUE THREAD

**Issue by ashleyse2016** [SpamExperts/mobile-app#43]
### Version information
1.0.4

### Steps to replicate

 1. login as admin to interface
 2. set date format to 28/06/2017 style
 3. save
 4 login to app as domain user 
 5. view messages

### Actual result

NULL shows instead of the `date` and `date and time` parts
### Expected result

To see the `date` and `date and time` parts
### Other notes
Please verify all date formats .

**Comment by alexkiro** [comment]
Internal ticket `#32522`
