### ISSUE TITLE
Attempting to log in as admin leads to infinite error message

### ISSUE THREAD

**Issue by tonyandrewmeyer** [SpamExperts/mobile-app#44]
### Version information

1.0.4

### Steps to replicate

 1. Attempt to log in as an admin.

### Actual result

An error message is display in a dialog with an "OK" button. Tapping the button shows the same error message. This repeats seemingly infinitely.

### Expected result

After tapping the button a single time, you can use different credentials.

**Comment by cristinav74** [comment]
This also blocks the app. Cleaning the cache won't solve the problem. The app must be reinstalled.

**Comment by nicolaeSE** [comment]
I think this no longer occurs. Can anyone test it and close the ticket?

**Comment by georges96** [comment]
Tested. It no longer goes in an infinit loop. Works as expected.
