### ISSUE TITLE
Improve error when attempting to log in as admin

### ISSUE THREAD

**Issue by tonyandrewmeyer** [SpamExperts/mobile-app#45]
When attempting to log in as an admin, the error message is "Unauthorized! You are not allowed to access this resource".

While we do want to simply add admin access at some point, for now it would be far better if this was a clearer error message, like "Error logging in: sorry, admin users are not able to use this app yet. Please log in as a domain or email user".

**Comment by cristinav74** [comment]
Issue tested. This is also covered with automated tests.
