### ISSUE TITLE
Login with "internal" user fail

### ISSUE THREAD

**Issue by cristinav74** [SpamExperts/mobile-app#46]
### Version information
1.0.4

### Steps to replicate

1. Hostname: filtering server
2. Username: internal
3. Password: `xxxxxxxxxxx`

### Actual result

`Login failed ! Creating default object from empty value.`

### Expected result

A successful login 

### Other notes

See attached screenshot
![screenshot_2017-07-13-13-03-21](https://user-images.githubusercontent.com/25306225/28162527-10f5a812-67d0-11e7-962e-fe35f5f6912e.jpg)

**Comment by nicolaeSE** [comment]
This was again related to the mobile app endpoints. The issue was fixed from Spampanel.

**Comment by cristinav74** [comment]
Issue tested. This is also covered with automated tests.
