### ISSUE TITLE
Actions on emails (e.g release, remove) aren't cleaning the quarantine from the hostname master

### ISSUE THREAD

**Issue by georges96** [SpamExperts/mobile-app#49]
### Version information
1e34617

### Steps to replicate

 1. Login in the application
 2. Go to the email list
 3. Release or remove email(s) or any other option including these two actions

### Actual result
 Emails are released or removed from the list but only on the application.
 On the spampanel they are still present in the spam quarantine. 
 Also the blacklisting and whitelisting are working but the secondary actions aren't (remove/release).
 The "purge quarantine" action is performing the erase of the entire spampanel quarantine but not on the application's email list. (for domain and email users)
### Expected result
 Emails should be erased from the spampanel quarantine too when release or removed action is performed.
 The "purge quarantine" should erase the emails from both spampanel quarantine and application's email list.(for domain and email users)
### Other notes
Checking logs shows no errors.
The actions of remove and release, performed on the spampanel quarantine, are visible in the application.

**Comment by alexkiro** [comment]
> On the spampanel they are still present in the spam quarantine.

@georges96 on what level are you checking the quarantine in SpamPanel?

**Comment by georges96** [comment]
@alexkiro on domain level and email level

**Comment by nicolaeSE** [comment]
Apparently the single actions work. It is very weird that when purging the quarantine the spams get removed from the Quarantine, however they still seem to be available somehow. This seems to be an endpoint issue and it should be corrected in the app's backend.

**Comment by nicolaeSE** [comment]
There is no issue here. Currently the purge action will clear the messages directly from the IMAP. Their status does not get updated hence the apparent issue. We need a feature ticket on the control panel side to improve the purge endpoint.
