### ISSUE TITLE
Design mock-up for dasboard

### ISSUE THREAD

**Issue by catalin-sc** [SpamExperts/mobile-app#6]
http://bit.ly/AppDashboardScreen

**Comment by tonyandrewmeyer** [comment]
It could be that I'm just totally biased from all the history, but it seems odd to have outgoing on the left and incoming on the right. Is there a reason you went with that?

**Comment by alexkiro** [comment]
> It could be that I'm just totally biased from all the history, but it seems odd to have outgoing on the left and incoming on the right. Is there a reason you went with that?

I think we should do this instead.

**Comment by ccatalinstoian** [comment]
While performing tests I noticed some issues:
1) That the available products are not displayed Incoming next to Outgoing starting with Incoming but they are displayed vertically. 
Please view the attached file:
file:///home/catalin/Link%20to%20Screenshot_2017-01-26-16-51-01.png
2) Also note that the SpamExperts logo is not displayed on the bottom of the Dashboard page. 
3) Note that on the left menu on the bottom Spamexperts is missing year `2017`.
4) While logging in with an email user it can be noticed that only `Incoming Filtering Quarantine` is visible on the Dashboard. If you manually login with the email user in a browser on your computer you will notice that Log Searc for outgoing is also present.

**Comment by ccatalinstoian** [comment]
5. Logout confirmation button from the Dashboard should have the same colour used in the rest of the mobile app and  also the modal dialog can be slightly changed by removing the header;
6. The title in Dashboard contains a exclamation character, for example  "Hello username!";
7. The header for the Dashboard page should be displayed on the page about 40% and the text in it centered like in the screenshot attached;
8. The icons for `Incoming Filtering Quarantine` and `Outgoing Filtering Quarantine` could be slightly smaller so they could fit more resolutions;
9. The space between the the header and the products available text "Your available products" is too small.

**Comment by ccatalinstoian** [comment]
1) The products available are placed next to each other as it should but note that when selected, the option only displays upper and lower borders;
2) Also found an issue related to the available products. It can be noticed that Outgoing product is slightly higher that Incoming;
3) Logout confirmation button from the Dashboard should have the same color used in the rest of the mobile app and also the modal dialog can be slightly changed by removing the header;
4) "Your available products" could be lowered a bit like it is in the screenshot from the description.
5) Also note that Lorentina noticed that when when rotating the screen the blue header is very close to "Your available products" text and it would be nice in that text would be lowered and the blue top header would be also increased in size.

**Comment by ccatalinstoian** [comment]
Verified the feature and the result is passed.
