### ISSUE TITLE
Design mock-up for list results screen

### ISSUE THREAD

**Issue by catalin-sc** [SpamExperts/mobile-app#7]
http://bit.ly/AppListResultsScreen

**Comment by Agoodfella** [comment]
The domain user wouldn't be able to scroll to the last message on the `outgoing spam messages` section.
Reproduction steps can be seen below:

1. Login as a domain user which already has incoming/outgoing spam messages in queue
2. Go to the outgoing spam messages section
3. Try viewing the spam message by tapping on a specific message > notice the error message > check a checkbox next to an email message and notice the second error message
4. Scroll to the last message

Notice that only the upper part of the email message is visible if the error messages are present on the screen and you can't scroll all the way down .

**Comment by Agoodfella** [comment]
The issue still occurs for me, both on portrait and horizontal view.

**Comment by Agoodfella** [comment]
Fix verified.
