### ISSUE TITLE
Design mock-up for message details screen

### ISSUE THREAD

**Issue by catalin-sc** [SpamExperts/mobile-app#8]
http://bit.ly/AppMessageDetailsScreen
http://bit.ly/AppMessageDetailsMRScreen
http://bit.ly/AppMessageDetailsAAScreen
http://bit.ly/AppMessageDetailsAttch

**Comment by CosminBadea1** [comment]
When trying to access message details screen from Outgoing Filtering Quarantine I get the following error message: "An error occured when trying to locate this message. This message might have been removed or released previously" even though the message wasn't removed or released.

**Comment by CosminBadea1** [comment]
In Outgoing Filtering Quarantine, when in detail screen I get the multiple recipients symbol(the rectangle with the number in it) even though the message was sent to a single person.

**Comment by CosminBadea1** [comment]
Cannot log in as super-admin in order to check the Outgoing Filtering Quarantine detail screen. I get logged out  from the app with the notification: Session expired.

Steps to reproduce:
 - create a super-admin in Spampanel;
 - log in on the app with the super-admin credentials;

**Comment by nicolaeSE** [comment]
I was not able to reproduce this behavior
